version: "3.9"

services:
  portfolio:
    build: ../portfolio
    container_name: portfolio
    ports:
      - "3000:3000"              # http://localhost:3000
    restart: unless-stopped
    networks:
      - app_net

  quiz:
    build: ../cybersecurity-quiz
    container_name: cybersecurity-quiz
    ports:
      - "4173:80"                # http://localhost:4173
    restart: unless-stopped
    networks:
      - app_net

  planner:
    build:
      context: ../cybersecurity-planner
      dockerfile: Dockerfile
    container_name: cybersecurity-planner
    ports:
      - "4174:80"                # http://localhost:4174
    restart: unless-stopped
    networks:
      - app_net

  db:
    image: postgres:16-alpine
    container_name: gantt-db
    environment:
      POSTGRES_USER: app_srv_gantt
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: gantt_dev
    volumes:
      - gantt_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_net
    # Pas de ports: la DB reste accessible seulement depuis le réseau interne

  backend:
    build:
      context: ../gantt/backend
      dockerfile: Dockerfile
    container_name: gantt-backend
    depends_on:
      - db
    environment:
      # le backend écoute sur 4940 dans le conteneur
      PORT: 4940
      # origine(s) autorisée(s) pour le frontend Gantt (et éventuellement le portfolio)
      CORS_ORIGIN: http://localhost:4941,http://localhost:3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: app_srv_gantt
      DB_PASS: ${DB_PASS}
      DB_NAME: gantt_dev
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4940:4940"              # API backend accessible sur http://localhost:4940
    restart: unless-stopped
    networks:
      - app_net

  frontend:
    build:
      context: ../gantt/frontend
    #    dockerfile: Dockerfile   # optionnel, si ton Dockerfile s’appelle bien 'Dockerfile'
      dockerfile: Dockerfile
    container_name: gantt-frontend
    depends_on:
      - backend
    environment:
      # côté frontend, l’API est accessible via le nom de service docker
      VITE_API_URL: "http://gantt-backend:4940"
    ports:
      - "4941:80"                # http://localhost:4941
    restart: unless-stopped
    networks:
      - app_net
  mario:
    build:
      context: ../mario-phaser
      dockerfile: Dockerfile
    container_name: mario-phaser
    ports:
      - "4175:80"          # http://localhost:4175
    restart: unless-stopped
    networks:
      - app_net

volumes:
  gantt_pgdata:

networks:
  app_net:
    driver: bridge
