// @ts-check
// ESLint config generated by `@nuxt/eslint`
// See: https://eslint.nuxt.com/
import withNuxt from "./.nuxt/eslint.config.mjs"

export default withNuxt(
  {
    files: ["**/*.{js,ts,vue}"],
    rules: {
      "vue/multi-word-component-names": "off",
      "@typescript-eslint/no-explicit-any": "warn",
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },
  {
    ignores: ["node_modules", ".nuxt", ".output", "dist", "public/docs/**"],
  }
)
