server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy vers ton backend pour toutes les routes /api
    location /api/ {
        proxy_pass http://backend:4940/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA fallback : toutes les routes front renvoient index.html
    location / {
        try_files $uri /index.html;
    }
}
